on:
  push:

jobs:
  notify-telegram:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - env:
          CMD: curl -sS https://world.dv8.org:7065/-509096909 -d
          MAIN: src/main.rs
        run: |
          $CMD "A Rustacian saved the day with:
           \"${{github.event.head_commit.message}}\"
           Tabs: $(<$MAIN tr -d \\n | tr \\t \\n | wc -l)
           unwrap()s: $(<$MAIN tr -d \\n | sed 's/unwrap()/\n/g' | wc -l)
           ${{github.event.head_commit.url}}"
